### PR TITLE
Add the initial content

### PR DESCRIPTION
**Pull request by bcamino**
Add the images and text for:
- cookies
- algorithm
- machine learning

### CODE REVIEW

**Comment by ChristinaMalcs** [comment]
Thanks Bruno - these changes look great. I shall approve now.

**Review by ChristinaMalcs — APPROVED** [review]
Approved!

**Review by ChristinaMalcs — APPROVED** [review]
Looks good - approved.

**Review by ChristinaMalcs — APPROVED** [review]
All set.

**Review by ChristinaMalcs — APPROVED** [review]

**Review by ChristinaMalcs — APPROVED** [review]
Confirming this is approved.

**Review by ChristinaMalcs — APPROVED** [review]
All set.

**Review by ChristinaMalcs — APPROVED** [review]
Done and approved.

**Review by ChristinaMalcs — APPROVED** [review]

**Comment by ChristinaMalcs** [comment]
Looks brilliant - thanks for this. Approved.

**Comment by electric-gap** [comment]
Hi @ChristinaMalcs, could you please review and merge this pull request?

**Pull request merged**
